services:
  # 1. Backend Service
  - type: web
    name: agrochain-server
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: server
    envVars:
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: NODEMAILER_EMAIL
        sync: false
      - key: NODEMAILER_PASS
        sync: false

  # 2. Client Static Site
  - type: web
    name: agrochain-client
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    rootDir: Client
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: agrochain-server
          property: host

  # 3. Admin Static Site
  - type: web
    name: agrochain-admin
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    rootDir: Admin
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: agrochain-server
          property: host
